// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/user.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_CreateUser_FullMethodName               = "/user.UserService/CreateUser"
	UserService_UpdateProgress_FullMethodName           = "/user.UserService/UpdateProgress"
	UserService_EnterTournament_FullMethodName          = "/user.UserService/EnterTournament"
	UserService_ClaimReward_FullMethodName              = "/user.UserService/ClaimReward"
	UserService_GetGlobalLeaderboard_FullMethodName     = "/user.UserService/GetGlobalLeaderboard"
	UserService_GetTournamentLeaderboard_FullMethodName = "/user.UserService/GetTournamentLeaderboard"
	UserService_GetTournamentRank_FullMethodName        = "/user.UserService/GetTournamentRank"
	UserService_GetUserTournaments_FullMethodName       = "/user.UserService/GetUserTournaments"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	UpdateProgress(ctx context.Context, in *UpdateProgressRequest, opts ...grpc.CallOption) (*UpdateProgressResponse, error)
	EnterTournament(ctx context.Context, in *EnterTournamentRequest, opts ...grpc.CallOption) (*EnterTournamentResponse, error)
	ClaimReward(ctx context.Context, in *ClaimRewardRequest, opts ...grpc.CallOption) (*ClaimRewardResponse, error)
	GetGlobalLeaderboard(ctx context.Context, in *GetGlobalLeaderboardRequest, opts ...grpc.CallOption) (*GetGlobalLeaderboardResponse, error)
	GetTournamentLeaderboard(ctx context.Context, in *GetTournamentLeaderboardRequest, opts ...grpc.CallOption) (*GetTournamentLeaderboardResponse, error)
	GetTournamentRank(ctx context.Context, in *GetTournamentRankRequest, opts ...grpc.CallOption) (*GetTournamentRankResponse, error)
	GetUserTournaments(ctx context.Context, in *GetUserTournamentsRequest, opts ...grpc.CallOption) (*GetUserTournamentsResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, UserService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateProgress(ctx context.Context, in *UpdateProgressRequest, opts ...grpc.CallOption) (*UpdateProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProgressResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) EnterTournament(ctx context.Context, in *EnterTournamentRequest, opts ...grpc.CallOption) (*EnterTournamentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnterTournamentResponse)
	err := c.cc.Invoke(ctx, UserService_EnterTournament_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ClaimReward(ctx context.Context, in *ClaimRewardRequest, opts ...grpc.CallOption) (*ClaimRewardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimRewardResponse)
	err := c.cc.Invoke(ctx, UserService_ClaimReward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetGlobalLeaderboard(ctx context.Context, in *GetGlobalLeaderboardRequest, opts ...grpc.CallOption) (*GetGlobalLeaderboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGlobalLeaderboardResponse)
	err := c.cc.Invoke(ctx, UserService_GetGlobalLeaderboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetTournamentLeaderboard(ctx context.Context, in *GetTournamentLeaderboardRequest, opts ...grpc.CallOption) (*GetTournamentLeaderboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTournamentLeaderboardResponse)
	err := c.cc.Invoke(ctx, UserService_GetTournamentLeaderboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetTournamentRank(ctx context.Context, in *GetTournamentRankRequest, opts ...grpc.CallOption) (*GetTournamentRankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTournamentRankResponse)
	err := c.cc.Invoke(ctx, UserService_GetTournamentRank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserTournaments(ctx context.Context, in *GetUserTournamentsRequest, opts ...grpc.CallOption) (*GetUserTournamentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTournamentsResponse)
	err := c.cc.Invoke(ctx, UserService_GetUserTournaments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	UpdateProgress(context.Context, *UpdateProgressRequest) (*UpdateProgressResponse, error)
	EnterTournament(context.Context, *EnterTournamentRequest) (*EnterTournamentResponse, error)
	ClaimReward(context.Context, *ClaimRewardRequest) (*ClaimRewardResponse, error)
	GetGlobalLeaderboard(context.Context, *GetGlobalLeaderboardRequest) (*GetGlobalLeaderboardResponse, error)
	GetTournamentLeaderboard(context.Context, *GetTournamentLeaderboardRequest) (*GetTournamentLeaderboardResponse, error)
	GetTournamentRank(context.Context, *GetTournamentRankRequest) (*GetTournamentRankResponse, error)
	GetUserTournaments(context.Context, *GetUserTournamentsRequest) (*GetUserTournamentsResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUserServiceServer) UpdateProgress(context.Context, *UpdateProgressRequest) (*UpdateProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProgress not implemented")
}
func (UnimplementedUserServiceServer) EnterTournament(context.Context, *EnterTournamentRequest) (*EnterTournamentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnterTournament not implemented")
}
func (UnimplementedUserServiceServer) ClaimReward(context.Context, *ClaimRewardRequest) (*ClaimRewardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimReward not implemented")
}
func (UnimplementedUserServiceServer) GetGlobalLeaderboard(context.Context, *GetGlobalLeaderboardRequest) (*GetGlobalLeaderboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGlobalLeaderboard not implemented")
}
func (UnimplementedUserServiceServer) GetTournamentLeaderboard(context.Context, *GetTournamentLeaderboardRequest) (*GetTournamentLeaderboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTournamentLeaderboard not implemented")
}
func (UnimplementedUserServiceServer) GetTournamentRank(context.Context, *GetTournamentRankRequest) (*GetTournamentRankResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTournamentRank not implemented")
}
func (UnimplementedUserServiceServer) GetUserTournaments(context.Context, *GetUserTournamentsRequest) (*GetUserTournamentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserTournaments not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateProgress(ctx, req.(*UpdateProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_EnterTournament_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnterTournamentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).EnterTournament(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_EnterTournament_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).EnterTournament(ctx, req.(*EnterTournamentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ClaimReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimRewardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ClaimReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ClaimReward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ClaimReward(ctx, req.(*ClaimRewardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetGlobalLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGlobalLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetGlobalLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetGlobalLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetGlobalLeaderboard(ctx, req.(*GetGlobalLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetTournamentLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTournamentLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetTournamentLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetTournamentLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetTournamentLeaderboard(ctx, req.(*GetTournamentLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetTournamentRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTournamentRankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetTournamentRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetTournamentRank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetTournamentRank(ctx, req.(*GetTournamentRankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserTournaments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTournamentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserTournaments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserTournaments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserTournaments(ctx, req.(*GetUserTournamentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "UpdateProgress",
			Handler:    _UserService_UpdateProgress_Handler,
		},
		{
			MethodName: "EnterTournament",
			Handler:    _UserService_EnterTournament_Handler,
		},
		{
			MethodName: "ClaimReward",
			Handler:    _UserService_ClaimReward_Handler,
		},
		{
			MethodName: "GetGlobalLeaderboard",
			Handler:    _UserService_GetGlobalLeaderboard_Handler,
		},
		{
			MethodName: "GetTournamentLeaderboard",
			Handler:    _UserService_GetTournamentLeaderboard_Handler,
		},
		{
			MethodName: "GetTournamentRank",
			Handler:    _UserService_GetTournamentRank_Handler,
		},
		{
			MethodName: "GetUserTournaments",
			Handler:    _UserService_GetUserTournaments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user.proto",
}
