// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Coins         int32                  `protobuf:"varint,3,opt,name=coins,proto3" json:"coins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CreateUserResponse) GetCoins() int32 {
	if x != nil {
		return x.Coins
	}
	return 0
}

type UpdateProgressRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProgressAmount int32                  `protobuf:"varint,2,opt,name=progress_amount,json=progressAmount,proto3" json:"progress_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateProgressRequest) Reset() {
	*x = UpdateProgressRequest{}
	mi := &file_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProgressRequest) ProtoMessage() {}

func (x *UpdateProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProgressRequest.ProtoReflect.Descriptor instead.
func (*UpdateProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProgressRequest) GetProgressAmount() int32 {
	if x != nil {
		return x.ProgressAmount
	}
	return 0
}

type UpdateProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Coins         int32                  `protobuf:"varint,3,opt,name=coins,proto3" json:"coins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProgressResponse) Reset() {
	*x = UpdateProgressResponse{}
	mi := &file_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProgressResponse) ProtoMessage() {}

func (x *UpdateProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProgressResponse.ProtoReflect.Descriptor instead.
func (*UpdateProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProgressResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProgressResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UpdateProgressResponse) GetCoins() int32 {
	if x != nil {
		return x.Coins
	}
	return 0
}

type EnterTournamentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterTournamentRequest) Reset() {
	*x = EnterTournamentRequest{}
	mi := &file_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterTournamentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterTournamentRequest) ProtoMessage() {}

func (x *EnterTournamentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterTournamentRequest.ProtoReflect.Descriptor instead.
func (*EnterTournamentRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *EnterTournamentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type EnterTournamentResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TournamentId   string                 `protobuf:"bytes,1,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	RemainingCoins int32                  `protobuf:"varint,2,opt,name=remaining_coins,json=remainingCoins,proto3" json:"remaining_coins,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnterTournamentResponse) Reset() {
	*x = EnterTournamentResponse{}
	mi := &file_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterTournamentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterTournamentResponse) ProtoMessage() {}

func (x *EnterTournamentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterTournamentResponse.ProtoReflect.Descriptor instead.
func (*EnterTournamentResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *EnterTournamentResponse) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

func (x *EnterTournamentResponse) GetRemainingCoins() int32 {
	if x != nil {
		return x.RemainingCoins
	}
	return 0
}

type ClaimRewardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRewardRequest) Reset() {
	*x = ClaimRewardRequest{}
	mi := &file_proto_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRewardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRewardRequest) ProtoMessage() {}

func (x *ClaimRewardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRewardRequest.ProtoReflect.Descriptor instead.
func (*ClaimRewardRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{6}
}

func (x *ClaimRewardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ClaimRewardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RewardCoins   int32                  `protobuf:"varint,2,opt,name=reward_coins,json=rewardCoins,proto3" json:"reward_coins,omitempty"`
	TotalCoins    int32                  `protobuf:"varint,3,opt,name=total_coins,json=totalCoins,proto3" json:"total_coins,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRewardResponse) Reset() {
	*x = ClaimRewardResponse{}
	mi := &file_proto_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRewardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRewardResponse) ProtoMessage() {}

func (x *ClaimRewardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRewardResponse.ProtoReflect.Descriptor instead.
func (*ClaimRewardResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{7}
}

func (x *ClaimRewardResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ClaimRewardResponse) GetRewardCoins() int32 {
	if x != nil {
		return x.RewardCoins
	}
	return 0
}

func (x *ClaimRewardResponse) GetTotalCoins() int32 {
	if x != nil {
		return x.TotalCoins
	}
	return 0
}

func (x *ClaimRewardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_proto_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{8}
}

func (x *LeaderboardEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeaderboardEntry) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *LeaderboardEntry) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type GetGlobalLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalLeaderboardRequest) Reset() {
	*x = GetGlobalLeaderboardRequest{}
	mi := &file_proto_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalLeaderboardRequest) ProtoMessage() {}

func (x *GetGlobalLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetGlobalLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{9}
}

type GetGlobalLeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalLeaderboardResponse) Reset() {
	*x = GetGlobalLeaderboardResponse{}
	mi := &file_proto_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalLeaderboardResponse) ProtoMessage() {}

func (x *GetGlobalLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*GetGlobalLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{10}
}

func (x *GetGlobalLeaderboardResponse) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetTournamentLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTournamentLeaderboardRequest) Reset() {
	*x = GetTournamentLeaderboardRequest{}
	mi := &file_proto_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTournamentLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTournamentLeaderboardRequest) ProtoMessage() {}

func (x *GetTournamentLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTournamentLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetTournamentLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{11}
}

func (x *GetTournamentLeaderboardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetTournamentLeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTournamentLeaderboardResponse) Reset() {
	*x = GetTournamentLeaderboardResponse{}
	mi := &file_proto_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTournamentLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTournamentLeaderboardResponse) ProtoMessage() {}

func (x *GetTournamentLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTournamentLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*GetTournamentLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetTournamentLeaderboardResponse) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetTournamentRankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTournamentRankRequest) Reset() {
	*x = GetTournamentRankRequest{}
	mi := &file_proto_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTournamentRankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTournamentRankRequest) ProtoMessage() {}

func (x *GetTournamentRankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTournamentRankRequest.ProtoReflect.Descriptor instead.
func (*GetTournamentRankRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetTournamentRankRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetTournamentRankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Rank          int32                  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTournamentRankResponse) Reset() {
	*x = GetTournamentRankResponse{}
	mi := &file_proto_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTournamentRankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTournamentRankResponse) ProtoMessage() {}

func (x *GetTournamentRankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTournamentRankResponse.ProtoReflect.Descriptor instead.
func (*GetTournamentRankResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{14}
}

func (x *GetTournamentRankResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTournamentRankResponse) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *GetTournamentRankResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type UserTournamentEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TournamentId  string                 `protobuf:"bytes,1,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Rank          int32                  `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	Claimed       bool                   `protobuf:"varint,5,opt,name=claimed,proto3" json:"claimed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTournamentEntry) Reset() {
	*x = UserTournamentEntry{}
	mi := &file_proto_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTournamentEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTournamentEntry) ProtoMessage() {}

func (x *UserTournamentEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTournamentEntry.ProtoReflect.Descriptor instead.
func (*UserTournamentEntry) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{15}
}

func (x *UserTournamentEntry) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

func (x *UserTournamentEntry) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UserTournamentEntry) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *UserTournamentEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *UserTournamentEntry) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

type GetUserTournamentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTournamentsRequest) Reset() {
	*x = GetUserTournamentsRequest{}
	mi := &file_proto_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTournamentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTournamentsRequest) ProtoMessage() {}

func (x *GetUserTournamentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTournamentsRequest.ProtoReflect.Descriptor instead.
func (*GetUserTournamentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserTournamentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserTournamentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tournaments   []*UserTournamentEntry `protobuf:"bytes,1,rep,name=tournaments,proto3" json:"tournaments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTournamentsResponse) Reset() {
	*x = GetUserTournamentsResponse{}
	mi := &file_proto_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTournamentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTournamentsResponse) ProtoMessage() {}

func (x *GetUserTournamentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTournamentsResponse.ProtoReflect.Descriptor instead.
func (*GetUserTournamentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserTournamentsResponse) GetTournaments() []*UserTournamentEntry {
	if x != nil {
		return x.Tournaments
	}
	return nil
}

var File_proto_user_proto protoreflect.FileDescriptor

const file_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x10proto/user.proto\x12\x04user\"6\n" +
	"\x11CreateUserRequest\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\"Y\n" +
	"\x12CreateUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x14\n" +
	"\x05coins\x18\x03 \x01(\x05R\x05coins\"Y\n" +
	"\x15UpdateProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fprogress_amount\x18\x02 \x01(\x05R\x0eprogressAmount\"]\n" +
	"\x16UpdateProgressResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x14\n" +
	"\x05coins\x18\x03 \x01(\x05R\x05coins\"1\n" +
	"\x16EnterTournamentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"g\n" +
	"\x17EnterTournamentResponse\x12#\n" +
	"\rtournament_id\x18\x01 \x01(\tR\ftournamentId\x12'\n" +
	"\x0fremaining_coins\x18\x02 \x01(\x05R\x0eremainingCoins\"-\n" +
	"\x12ClaimRewardRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x8c\x01\n" +
	"\x13ClaimRewardResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\freward_coins\x18\x02 \x01(\x05R\vrewardCoins\x12\x1f\n" +
	"\vtotal_coins\x18\x03 \x01(\x05R\n" +
	"totalCoins\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"d\n" +
	"\x10LeaderboardEntry\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\"\x1d\n" +
	"\x1bGetGlobalLeaderboardRequest\"P\n" +
	"\x1cGetGlobalLeaderboardResponse\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.user.LeaderboardEntryR\aentries\":\n" +
	"\x1fGetTournamentLeaderboardRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"T\n" +
	" GetTournamentLeaderboardResponse\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.user.LeaderboardEntryR\aentries\"3\n" +
	"\x18GetTournamentRankRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"^\n" +
	"\x19GetTournamentRankResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x05R\x04rank\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\"\x99\x01\n" +
	"\x13UserTournamentEntry\x12#\n" +
	"\rtournament_id\x18\x01 \x01(\tR\ftournamentId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x12\n" +
	"\x04rank\x18\x04 \x01(\x05R\x04rank\x12\x18\n" +
	"\aclaimed\x18\x05 \x01(\bR\aclaimed\"4\n" +
	"\x19GetUserTournamentsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"Y\n" +
	"\x1aGetUserTournamentsResponse\x12;\n" +
	"\vtournaments\x18\x01 \x03(\v2\x19.user.UserTournamentEntryR\vtournaments2\xa8\x05\n" +
	"\vUserService\x12?\n" +
	"\n" +
	"CreateUser\x12\x17.user.CreateUserRequest\x1a\x18.user.CreateUserResponse\x12K\n" +
	"\x0eUpdateProgress\x12\x1b.user.UpdateProgressRequest\x1a\x1c.user.UpdateProgressResponse\x12N\n" +
	"\x0fEnterTournament\x12\x1c.user.EnterTournamentRequest\x1a\x1d.user.EnterTournamentResponse\x12B\n" +
	"\vClaimReward\x12\x18.user.ClaimRewardRequest\x1a\x19.user.ClaimRewardResponse\x12]\n" +
	"\x14GetGlobalLeaderboard\x12!.user.GetGlobalLeaderboardRequest\x1a\".user.GetGlobalLeaderboardResponse\x12i\n" +
	"\x18GetTournamentLeaderboard\x12%.user.GetTournamentLeaderboardRequest\x1a&.user.GetTournamentLeaderboardResponse\x12T\n" +
	"\x11GetTournamentRank\x12\x1e.user.GetTournamentRankRequest\x1a\x1f.user.GetTournamentRankResponse\x12W\n" +
	"\x12GetUserTournaments\x12\x1f.user.GetUserTournamentsRequest\x1a .user.GetUserTournamentsResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_user_proto_rawDescOnce sync.Once
	file_proto_user_proto_rawDescData []byte
)

func file_proto_user_proto_rawDescGZIP() []byte {
	file_proto_user_proto_rawDescOnce.Do(func() {
		file_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)))
	})
	return file_proto_user_proto_rawDescData
}

var file_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_user_proto_goTypes = []any{
	(*CreateUserRequest)(nil),                // 0: user.CreateUserRequest
	(*CreateUserResponse)(nil),               // 1: user.CreateUserResponse
	(*UpdateProgressRequest)(nil),            // 2: user.UpdateProgressRequest
	(*UpdateProgressResponse)(nil),           // 3: user.UpdateProgressResponse
	(*EnterTournamentRequest)(nil),           // 4: user.EnterTournamentRequest
	(*EnterTournamentResponse)(nil),          // 5: user.EnterTournamentResponse
	(*ClaimRewardRequest)(nil),               // 6: user.ClaimRewardRequest
	(*ClaimRewardResponse)(nil),              // 7: user.ClaimRewardResponse
	(*LeaderboardEntry)(nil),                 // 8: user.LeaderboardEntry
	(*GetGlobalLeaderboardRequest)(nil),      // 9: user.GetGlobalLeaderboardRequest
	(*GetGlobalLeaderboardResponse)(nil),     // 10: user.GetGlobalLeaderboardResponse
	(*GetTournamentLeaderboardRequest)(nil),  // 11: user.GetTournamentLeaderboardRequest
	(*GetTournamentLeaderboardResponse)(nil), // 12: user.GetTournamentLeaderboardResponse
	(*GetTournamentRankRequest)(nil),         // 13: user.GetTournamentRankRequest
	(*GetTournamentRankResponse)(nil),        // 14: user.GetTournamentRankResponse
	(*UserTournamentEntry)(nil),              // 15: user.UserTournamentEntry
	(*GetUserTournamentsRequest)(nil),        // 16: user.GetUserTournamentsRequest
	(*GetUserTournamentsResponse)(nil),       // 17: user.GetUserTournamentsResponse
}
var file_proto_user_proto_depIdxs = []int32{
	8,  // 0: user.GetGlobalLeaderboardResponse.entries:type_name -> user.LeaderboardEntry
	8,  // 1: user.GetTournamentLeaderboardResponse.entries:type_name -> user.LeaderboardEntry
	15, // 2: user.GetUserTournamentsResponse.tournaments:type_name -> user.UserTournamentEntry
	0,  // 3: user.UserService.CreateUser:input_type -> user.CreateUserRequest
	2,  // 4: user.UserService.UpdateProgress:input_type -> user.UpdateProgressRequest
	4,  // 5: user.UserService.EnterTournament:input_type -> user.EnterTournamentRequest
	6,  // 6: user.UserService.ClaimReward:input_type -> user.ClaimRewardRequest
	9,  // 7: user.UserService.GetGlobalLeaderboard:input_type -> user.GetGlobalLeaderboardRequest
	11, // 8: user.UserService.GetTournamentLeaderboard:input_type -> user.GetTournamentLeaderboardRequest
	13, // 9: user.UserService.GetTournamentRank:input_type -> user.GetTournamentRankRequest
	16, // 10: user.UserService.GetUserTournaments:input_type -> user.GetUserTournamentsRequest
	1,  // 11: user.UserService.CreateUser:output_type -> user.CreateUserResponse
	3,  // 12: user.UserService.UpdateProgress:output_type -> user.UpdateProgressResponse
	5,  // 13: user.UserService.EnterTournament:output_type -> user.EnterTournamentResponse
	7,  // 14: user.UserService.ClaimReward:output_type -> user.ClaimRewardResponse
	10, // 15: user.UserService.GetGlobalLeaderboard:output_type -> user.GetGlobalLeaderboardResponse
	12, // 16: user.UserService.GetTournamentLeaderboard:output_type -> user.GetTournamentLeaderboardResponse
	14, // 17: user.UserService.GetTournamentRank:output_type -> user.GetTournamentRankResponse
	17, // 18: user.UserService.GetUserTournaments:output_type -> user.GetUserTournamentsResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_user_proto_init() }
func file_proto_user_proto_init() {
	if File_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_proto_goTypes,
		DependencyIndexes: file_proto_user_proto_depIdxs,
		MessageInfos:      file_proto_user_proto_msgTypes,
	}.Build()
	File_proto_user_proto = out.File
	file_proto_user_proto_goTypes = nil
	file_proto_user_proto_depIdxs = nil
}
